export const TASKS_REQUEST = "TASKS_REQUEST";
export const TASKS_SUCCESS = "TASKS_SUCCESS";
export const TASKS_FAILURE = "TASKS_FAILURE";

export const FORECAST_REQUEST = "FORECAST_REQUEST";
export const FORECAST_SUCCESS = "FORECAST_SUCCESS";
export const FORECAST_FAILURE = "FORECAST_FAILURE";

export const FORECAST_LOCATION = "FORECAST_LOCATION";

export const DELETE_TASK_REQUEST = "DELETE_TASK_REQUEST";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
