export const TASKS_REQUEST = "TASKS_REQUEST";
export const TASKS_SUCCESS = "TASKS_SUCCESS";
export const TASKS_FAILURE = "TASKS_FAILURE";

export const FORECAST_REQUEST = "FORECAST_REQUEST";
export const FORECAST_SUCCESS = "FORECAST_SUCCESS";
export const FORECAST_FAILURE = "FORECAST_FAILURE";

export const FORECAST_LOCATION = "FORECAST_LOCATION";

export const DELETE_TASK_REQUEST = "DELETE_TASK_REQUEST";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";

export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";

export const HANDLE_CHANGE = "HANDLE_CHANGE";

export const CREATE_TASK_BEGIN = "CREATE_TASK_BEGIN";
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";
export const CREATE_TASK_ERROR = "CREATE_TASK_ERROR";
